apiVersion: v1
kind: Namespace
metadata:
  name: dasasdasd-staging
  labels:
    environment-id: env_4e29c848-9c96-45c6-8bf1-c982560c0174
    project-id: project_50ac997a-1887-4252-ba98-d0ce5e5a86bd
    project-name: dasasdasd
    environment-name: staging
    organization-id: org_c50d7b26-1f2a-4a6e-b11e-469a86e002c8
