apiVersion: v1
kind: Namespace
metadata:
  name: gdfhdfghdfg-prod
  labels:
    environment-id: env_83a621c8-5dd8-4daf-afc7-8f7a1bd6a22b
    project-id: project_df3b6076-85d2-40db-9f1d-cb86aaaa8b7c
    project-name: gdfhdfghdfg
    environment-name: prod
    organization-id: org_c50d7b26-1f2a-4a6e-b11e-469a86e002c8
